baseURL = "https://www.bizone.org"
languageCode = "en"
defaultContentLanguage = "en"
title = "Bisexuality-Aware Professionals Directory"
#theme = "bizone"
paginate = 10
timeout = 200000

[outputFormats.JSON]
	MediaType              = "application/json"
	BaseName               = "index"
	IsHTML                 = false
	IsPlainText            = true
	noUgly                 = false
	Rel                    = "alternate"

[outputs]
page = [ "HTML" ]
home = [ "HTML" ]
section = [ "HTML" ]
taxonomy = [ "HTML", "RSS" ]
term = [ "HTML" ]


[params]
lazyload = 1
debug = 0
wysiwyg = 0
branding = 3
vue = 0


[taxonomies]
	category = "categories"
	country = "countries"
	region = "regions"

[markup]
	[markup.tableOfContents]
		endLevel = 3
		ordered = false
		startLevel = 2
	[markup.goldmark.renderer]
		unsafe= true

[module]
[[module.imports]]
path = "github.com/scrollodex/hugo-modules"
